
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class OleDbEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.2.0.7)

Imports System
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _ivreferm
	Inherits OleDbEntity

		Public Sub New() 
			Me.QuerySource = "ivreferm"
			Me.MappingName = "ivreferm"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
	
	Public Overrides Function GetAutoKeyColumn() As String
			Return "ref_code"
	End Function
	
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_ivrefermLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
	Public Overridable Function LoadByPrimaryKey(ByVal Ref_code As Integer) As Boolean

		Dim parameters As ListDictionary = New ListDictionary()
		parameters.Add(_ivreferm.Parameters.Ref_code, Ref_code)

		
		Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_ivrefermLoadByPrimaryKey]", parameters)

	End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property Ref_code As OleDbParameter
			Get
				Return New OleDbParameter("@Ref_code", OleDbType.Integer, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Item_code As OleDbParameter
			Get
				Return New OleDbParameter("@Item_code", OleDbType.VarChar, 10)
			End Get
		End Property
		
		Public Shared ReadOnly Property Prov_code As OleDbParameter
			Get
				Return New OleDbParameter("@Prov_code", OleDbType.Integer, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Refer As OleDbParameter
			Get
				Return New OleDbParameter("@Refer", OleDbType.VarChar, 15)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const Ref_code As String = "ref_code"
        Public Const Item_code As String = "item_code"
        Public Const Prov_code As String = "prov_code"
        Public Const Refer As String = "refer"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(Ref_code) = _ivreferm.PropertyNames.Ref_code
				ht(Item_code) = _ivreferm.PropertyNames.Item_code
				ht(Prov_code) = _ivreferm.PropertyNames.Prov_code
				ht(Refer) = _ivreferm.PropertyNames.Refer

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const Ref_code As String = "Ref_code"
        Public Const Item_code As String = "Item_code"
        Public Const Prov_code As String = "Prov_code"
        Public Const Refer As String = "Refer"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(Ref_code) = _ivreferm.ColumnNames.Ref_code
				ht(Item_code) = _ivreferm.ColumnNames.Item_code
				ht(Prov_code) = _ivreferm.ColumnNames.Prov_code
				ht(Refer) = _ivreferm.ColumnNames.Refer

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const Ref_code As String = "s_Ref_code"
        Public Const Item_code As String = "s_Item_code"
        Public Const Prov_code As String = "s_Prov_code"
        Public Const Refer As String = "s_Refer"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property Ref_code As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.Ref_code)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.Ref_code, Value)
			End Set
		End Property

		Public Overridable Property Item_code As String
			Get
				Return MyBase.GetString(ColumnNames.Item_code)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Item_code, Value)
			End Set
		End Property

		Public Overridable Property Prov_code As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.Prov_code)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.Prov_code, Value)
			End Set
		End Property

		Public Overridable Property Refer As String
			Get
				Return MyBase.GetString(ColumnNames.Refer)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Refer, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_Ref_code As String
			Get
				If Me.IsColumnNull(ColumnNames.Ref_code) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.Ref_code)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Ref_code)
				Else
					Me.Ref_code = MyBase.SetIntegerAsString(ColumnNames.Ref_code, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Item_code As String
			Get
				If Me.IsColumnNull(ColumnNames.Item_code) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Item_code)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Item_code)
				Else
					Me.Item_code = MyBase.SetStringAsString(ColumnNames.Item_code, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Prov_code As String
			Get
				If Me.IsColumnNull(ColumnNames.Prov_code) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.Prov_code)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Prov_code)
				Else
					Me.Prov_code = MyBase.SetIntegerAsString(ColumnNames.Prov_code, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Refer As String
			Get
				If Me.IsColumnNull(ColumnNames.Refer) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Refer)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Refer)
				Else
					Me.Refer = MyBase.SetStringAsString(ColumnNames.Refer, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property Ref_code() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Ref_code, Parameters.Ref_code)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Item_code() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Item_code, Parameters.Item_code)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Prov_code() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Prov_code, Parameters.Prov_code)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Refer() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Refer, Parameters.Refer)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property Ref_code() As WhereParameter 
			Get
				If _Ref_code_W Is Nothing Then
					_Ref_code_W = TearOff.Ref_code
				End If
				Return _Ref_code_W
			End Get
		End Property

		Public ReadOnly Property Item_code() As WhereParameter 
			Get
				If _Item_code_W Is Nothing Then
					_Item_code_W = TearOff.Item_code
				End If
				Return _Item_code_W
			End Get
		End Property

		Public ReadOnly Property Prov_code() As WhereParameter 
			Get
				If _Prov_code_W Is Nothing Then
					_Prov_code_W = TearOff.Prov_code
				End If
				Return _Prov_code_W
			End Get
		End Property

		Public ReadOnly Property Refer() As WhereParameter 
			Get
				If _Refer_W Is Nothing Then
					_Refer_W = TearOff.Refer
				End If
				Return _Refer_W
			End Get
		End Property

		Private _Ref_code_W As WhereParameter = Nothing
		Private _Item_code_W As WhereParameter = Nothing
		Private _Prov_code_W As WhereParameter = Nothing
		Private _Refer_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_Ref_code_W = Nothing
			_Item_code_W = Nothing
			_Prov_code_W = Nothing
			_Refer_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property Ref_code() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Ref_code, Parameters.Ref_code)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Item_code() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Item_code, Parameters.Item_code)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Prov_code() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Prov_code, Parameters.Prov_code)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Refer() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Refer, Parameters.Refer)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property Ref_code() As AggregateParameter 
			Get
				If _Ref_code_W Is Nothing Then
					_Ref_code_W = TearOff.Ref_code
				End If
				Return _Ref_code_W
			End Get
		End Property

		Public ReadOnly Property Item_code() As AggregateParameter 
			Get
				If _Item_code_W Is Nothing Then
					_Item_code_W = TearOff.Item_code
				End If
				Return _Item_code_W
			End Get
		End Property

		Public ReadOnly Property Prov_code() As AggregateParameter 
			Get
				If _Prov_code_W Is Nothing Then
					_Prov_code_W = TearOff.Prov_code
				End If
				Return _Prov_code_W
			End Get
		End Property

		Public ReadOnly Property Refer() As AggregateParameter 
			Get
				If _Refer_W Is Nothing Then
					_Refer_W = TearOff.Refer
				End If
				Return _Refer_W
			End Get
		End Property

		Private _Ref_code_W As AggregateParameter = Nothing
		Private _Item_code_W As AggregateParameter = Nothing
		Private _Prov_code_W As AggregateParameter = Nothing
		Private _Refer_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_Ref_code_W = Nothing
		_Item_code_W = Nothing
		_Prov_code_W = Nothing
		_Refer_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As OleDbCommand = New OleDbCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_ivrefermInsert]" 
	    
		CreateParameters(cmd)
		    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As OleDbCommand = New OleDbCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_ivrefermUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As OleDbCommand = New OleDbCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_ivrefermDelete]" 
		
		Dim p As OleDbParameter
		p = cmd.Parameters.Add(Parameters.Ref_code)
		p.SourceColumn = ColumnNames.Ref_code
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As OleDbCommand)
	
		Dim p As OleDbParameter
		p = cmd.Parameters.Add(Parameters.Ref_code)
		p.SourceColumn = ColumnNames.Ref_code
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Item_code)
		p.SourceColumn = ColumnNames.Item_code
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Prov_code)
		p.SourceColumn = ColumnNames.Prov_code
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Refer)
		p.SourceColumn = ColumnNames.Refer
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

