' Generated by MyGeneration Version # (1.2.0.7)
Public Class ccinvcem
    Inherits _ccinvcem
    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!invce_serial.ToString.Trim, oRow!suc_code.ToString.Trim) = False Then
            Me.AddNew()
        End If

        '// Salvar Factura
        With Me
            If Not oRow!type_code Is DBNull.Value Then .type_code = oRow!type_code
            If Not oRow!invce_no Is DBNull.Value Then .invce_no = oRow!invce_no
            If Not oRow!term_code Is DBNull.Value Then .term_code = oRow!term_code
            If Not oRow!cust_code Is DBNull.Value Then .cust_code = oRow!cust_code
            If Not oRow!invce_date Is DBNull.Value Then .invce_date = oRow!invce_date
            If Not oRow!detail Is DBNull.Value Then .detail = oRow!detail
            If Not oRow!due_date Is DBNull.Value Then .due_date = oRow!due_date
            If Not oRow!amount Is DBNull.Value Then .amount = oRow!amount
            If Not oRow!itbis Is DBNull.Value Then .itbis = oRow!itbis
            If Not oRow!amount_grab Is DBNull.Value Then .amount_grab = oRow!amount_grab
            If Not oRow!amount_excent Is DBNull.Value Then .amount_excent = oRow!amount_excent
            If Not oRow!cargo_banc Is DBNull.Value Then .cargo_banc = oRow!cargo_banc
            If Not oRow!cargo_desc Is DBNull.Value Then .cargo_desc = oRow!cargo_desc
            If Not oRow!excento Is DBNull.Value Then .excento = oRow!excento
            If Not oRow!impto Is DBNull.Value Then .impto = oRow!impto
            .invce_status = 2
            If Not oRow!total_amount Is DBNull.Value Then .total_amount = oRow!total_amount
            If Not oRow!invce_ncf Is DBNull.Value Then .invce_ncf = oRow!invce_ncf
            If Not oRow!vend_code Is DBNull.Value Then .vend_code = oRow!vend_code
            If Not oRow!chequera Is DBNull.Value Then .chequera = oRow!chequera
            If Not oRow!suc_code Is DBNull.Value Then .suc_code = oRow!suc_code
            If Not oRow!invce_datetran Is DBNull.Value Then .invce_datetran = oRow!invce_datetran
            If Not oRow!invce_create Is DBNull.Value Then .invce_create = oRow!invce_create
            .Save()
        End With
        Return True
    End Function
End Class
