
' Generated by MyGeneration Version # (1.3.0.3)

Public Class cgtranrd 
	Inherits _cgtranrd

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!tranr_serial, oRow!line_no,oRow!acct_no,oRow!suc_code) = False Then
            Me.AddNew()
            ''Me.Existencia = 0
        End If

        '// Salvar Producto
        With Me
            If Not oRow!tranr_serial Is DBNull.Value Then .tranr_serial = oRow!tranr_serial
            If Not oRow!tranr_detail Is DBNull.Value Then .tranr_detail = oRow!tranr_detail
            If Not oRow!acct_no Is DBNull.Value Then .acct_no = oRow!acct_no.ToString.Trim
            If Not oRow!suc_code Is DBNull.Value Then .suc_code = oRow!suc_code
            If Not oRow!dept_code Is DBNull.Value Then .dept_code = oRow!dept_code
            If Not oRow!debit_credit Is DBNull.Value Then .debit_credit = oRow!debit_credit
            If Not oRow!line_no Is DBNull.Value Then .line_no = oRow!line_no
            If Not oRow!amount Is DBNull.Value Then .amount = oRow!amount

            .Save()
        End With
    End Function
End Class
