
' Generated by MyGeneration Version # (1.3.0.3)

Public Class cgtranrm 
	Inherits _cgtranrm

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!tranr_serial, oRow!suc_code) = False Then
            Me.AddNew()
        End If

        '// Salvar Entrada
        With Me
            If Not oRow!tranr_serial Is DBNull.Value Then .tranr_serial = oRow!tranr_serial
            If Not oRow!tran_type Is DBNull.Value Then .tran_type = oRow!tran_type.ToString.Trim
            If Not oRow!perdr_year Is DBNull.Value Then .perdr_year = oRow!perdr_year
            If Not oRow!perdr_num Is DBNull.Value Then .perdr_num = oRow!perdr_num
            If Not oRow!orign_code Is DBNull.Value Then .orign_code = oRow!orign_code
            If Not oRow!tran_number Is DBNull.Value Then .tran_number = oRow!tran_number
            If Not oRow!tran_date Is DBNull.Value Then .tran_date = oRow!tran_date
            If Not oRow!date_created Is DBNull.Value Then .date_created = oRow!date_created
            If Not oRow!tran_descr Is DBNull.Value Then .tran_descr = oRow!tran_descr
            If Not oRow!tran_status Is DBNull.Value Then .tran_status = oRow!tran_status
            If Not oRow!userid Is DBNull.Value Then .userid = oRow!userid
            If Not oRow!tran_reverse Is DBNull.Value Then .tran_reverse = oRow!tran_reverse
            If Not oRow!tran_refer Is DBNull.Value Then .tran_refer = oRow!tran_refer
            If Not oRow!suc_code Is DBNull.Value Then .suc_code = oRow!suc_code

            .Save()
        End With

        Return True

    End Function
End Class
