
' Generated by MyGeneration Version # (1.3.0.3)

Public Class cpordnm 
	Inherits _cpordnm

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!ordn_serial) = False Then
            Me.AddNew()
        End If

        '// Salvar Entrada
        With Me
            If Not oRow!ordn_serial Is DBNull.Value Then .ordn_serial = oRow!ordn_serial
            If Not oRow!type_code Is DBNull.Value Then .type_code = oRow!type_code.ToString.Trim
            If Not oRow!prov_code Is DBNull.Value Then .prov_code = oRow!prov_code
            If Not oRow!ordn_date Is DBNull.Value Then .ordn_date = oRow!ordn_date
            If Not oRow!ordn_number Is DBNull.Value Then .ordn_number = oRow!ordn_number
            If Not oRow!ordn_note Is DBNull.Value Then .ordn_note = oRow!ordn_note
            If Not oRow!ordn_status Is DBNull.Value Then .ordn_status = oRow!ordn_status
            If Not oRow!total_amount Is DBNull.Value Then .total_amount = oRow!total_amount
            If Not oRow!whse_code Is DBNull.Value Then .whse_code = oRow!whse_code
            If Not oRow!total_itbis Is DBNull.Value Then .total_itbis = oRow!total_itbis
            If Not oRow!maximo Is DBNull.Value Then .maximo = oRow!maximo
            If Not oRow!minimo Is DBNull.Value Then .minimo = oRow!minimo
            If Not oRow!reorden Is DBNull.Value Then .reorden = oRow!reorden
            If Not oRow!periodo Is DBNull.Value Then .periodo = oRow!periodo
            If Not oRow!suc_code Is DBNull.Value Then .suc_code = oRow!suc_code

            .Save()
        End With

        Return True

    End Function
End Class
