
' Generated by MyGeneration Version # (1.3.0.3)

Public Class cpordnd 
	Inherits _cpordnd

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!ordn_serial, oRow!item_code) = False Then
            Me.AddNew()
            ''Me.Existencia = 0
        End If

        '// Salvar Producto
        With Me
            If Not oRow!ordn_serial Is DBNull.Value Then .ordn_serial = oRow!ordn_serial
            If Not oRow!whse_code Is DBNull.Value Then .whse_code = oRow!whse_code
            If Not oRow!item_code Is DBNull.Value Then .item_code = oRow!item_code
            If Not oRow!ref_code Is DBNull.Value Then .ref_code = oRow!ref_code
            If Not oRow!Qty Is DBNull.Value Then .Qty = oRow!Qty.ToString.Trim
            If Not oRow!itbis Is DBNull.Value Then .itbis = oRow!itbis
            If Not oRow!promedio Is DBNull.Value Then .promedio = oRow!promedio
            If Not oRow!sugerida Is DBNull.Value Then .sugerida = oRow!sugerida
            If Not oRow!diasventa Is DBNull.Value Then .diasventa = oRow!diasventa
            If Not oRow!reorden Is DBNull.Value Then .reorden = oRow!reorden
            If Not oRow!unit_code Is DBNull.Value Then .unit_code = oRow!unit_code
            If Not oRow!existencia Is DBNull.Value Then .existencia = oRow!existencia
            If Not oRow!suc_code Is DBNull.Value Then .suc_code = oRow!suc_code
            .Save()
        End With
    End Function
End Class
