
' Generated by MyGeneration Version # (1.2.0.7)
Imports SGT.Inventario.Common
Imports SGT.Inventario.Entidades

Public Class iventrdd 
	Inherits _iventrdd

    Public Function CreateFromRowSalida(ByVal oRow As DataRow, _
                                        ByVal pEntrSerial As Integer, _
                                        ByVal pTotalAmount As Decimal, _
                                        ByVal pItbisAmount As Decimal) As Boolean
        Dim intSucCode As Integer
        Try

            Me.Where.Entr_serial.Value = pEntrSerial
            Me.Where.Item_code.Value = oRow!item_code

            Me.Query.Load()

            If Me.RowCount <= 0 Then
                Me.AddNew()
            End If

            intSucCode = System.Configuration.ConfigurationSettings.AppSettings.Get("LibxScDefault")

            Me.Entr_serial = pEntrSerial
            Me.Item_code = oRow!item_code
            Me.Line_no = oRow!line_no
            Me.Whse_code = oRow!whse_code
            Me.Unit_code = oRow!unit_code
            Me.Qty = oRow!qty
            Me.Costo = oRow!costo
            Me.Purch_unit_cost = oRow!costo
            Me.Sales_price = oRow!price
            Me.Price = oRow!price
            Me.Itbis = oRow!itbis
            Me.Suc_code = intSucCode
            Me.Factor = oRow!factor


            '//////////////////////////////////
            '// Calcular Precios y Costos
            If LibX.Data.Manager.Connection Is Nothing OrElse LibX.Data.Manager.Connection.State = ConnectionState.Closed Then
                LibX.Data.Manager.OpenConnection()
            End If

            Dim oParam As New Articulo.ParametrosCostosLocales
            Dim mArticulo As New Articulo

            With oParam
                .Producto = Me.Item_code
                .Almacen = Me.Whse_code
                .Costo = Me.Costo
                .Cantidad = Me.Qty
                .Ofertas = 0
                .UnidadCompra = Me.Unit_code
                .Descuento = 0
                .ISC = 0

                .incluirOFERTA = False
                .IncluirITBIS = False
                .incluirISC = False
                .IncluirDescuento = False

                .TotalFactura = pTotalAmount
                .Importe = (Me.Qty * Me.Costo) + Me.Itbis
                .TotalITBIS = pItbisAmount
            End With

            If mArticulo.CalcularCostoLocal(oParam) = True Then
                Me.Price = oParam.ValoresRetorno.Precio
                Me.Sales_price = Decimal.Round(oParam.ValoresRetorno.Precio, 2)
                Me.Purch_unit_cost = Decimal.Round(oParam.ValoresRetorno.costo, 2)
                Me.Itbis = Decimal.Round(oParam.ValoresRetorno.Itbis, 2)
            End If

            LibX.Data.Manager.Connection.Close()
            '/////////////////////////////

            Me.Save()

            Return True
        Catch ex As Exception
            Throw
        End Try

    End Function
End Class
