
' Generated by MyGeneration Version # (1.3.0.3)

Public Class ivitemd 
	Inherits _ivitemd

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!whse_code, oRow!item_code) = False Then
            Me.AddNew()
            Me.Existencia = 0
        End If

        '// Salvar Producto
        With Me
            If Not oRow!Whse_code Is DBNull.Value Then .Whse_code = oRow!Whse_code
            If Not oRow!Item_code Is DBNull.Value Then .Item_code = oRow!Item_code
            If Not oRow!Purch_cost Is DBNull.Value Then .Purch_cost = oRow!Purch_cost
            If Not oRow!Porc_isc Is DBNull.Value Then .Porc_isc = oRow!Porc_isc
            If Not oRow!Last_cost Is DBNull.Value Then .Last_cost = oRow!Last_cost
            If Not oRow!Avg_cost Is DBNull.Value Then .Avg_cost = oRow!Avg_cost
            '// If Not oRow!Loc_row Is DBNull.Value Then .Loc_row = oRow!Loc_row
            '// If Not oRow!Loc_col Is DBNull.Value Then .Loc_col = oRow!Loc_col
            '// If Not oRow!Estante Is DBNull.Value Then .Estante = oRow!Estante
            If Not oRow!Price Is DBNull.Value Then .Price = oRow!Price
            If Not oRow!Benef Is DBNull.Value Then .Benef = oRow!Benef
            '// If Not oRow!BackOrder Is DBNull.Value Then .BackOrder = oRow!BackOrder
            '// If Not oRow!Existencia Is DBNull.Value Then .Existencia = oRow!Existencia
            '// If Not oRow!datelast_purch Is DBNull.Value Then .datelast_purch = oRow!datelast_purch
            '// If Not oRow!datelast_sales Is DBNull.Value Then .datelast_sales = oRow!datelast_sales
            If Not oRow!Taxable Is DBNull.Value Then .Taxable = oRow!Taxable
            If Not oRow!Rounded Is DBNull.Value Then .Rounded = oRow!Rounded
            If Not oRow!Rorder_point Is DBNull.Value Then .Rorder_point = oRow!Rorder_point
            If Not oRow!Existencia_min Is DBNull.Value Then .Existencia_min = oRow!Existencia_min
            If Not oRow!Exitencia_max Is DBNull.Value Then .Exitencia_max = oRow!Exitencia_max
            If Not oRow!Cant_pedida Is DBNull.Value Then .Cant_pedida = oRow!Cant_pedida
            If Not oRow!Cant_recibida Is DBNull.Value Then .Cant_recibida = oRow!Cant_recibida
            '// If Not oRow!Numero_orden Is DBNull.Value Then .Numero_orden = oRow!Numero_orden
            '// If Not oRow!Frizado_inv Is DBNull.Value Then .Frizado_inv = oRow!Frizado_inv
            If Not oRow!Aplica_dscnt Is DBNull.Value Then .Aplica_dscnt = oRow!Aplica_dscnt.ToString.Trim
            '// If Not oRow!Fecha_frizado Is DBNull.Value Then .Fecha_frizado = oRow!Fecha_frizado
            '//If Not oRow!Limite_frizado Is DBNull.Value Then .Limite_frizado = oRow!Limite_frizado
            '// .SetColumnNull(.ColumnNames.Fecha_conteo)
            '//If Not oRow!Ultima_trans Is DBNull.Value Then .Ultima_trans = oRow!Ultima_trans
            ''//If Not oRow!Vencimiento Is DBNull.Value Then .Vencimiento = oRow!Vencimiento
            If Not oRow!Disc_pct Is DBNull.Value Then .Disc_pct = oRow!Disc_pct
            .Save()
        End With
    End Function
End Class
