' Generated by MyGeneration Version # (1.3.0.3)
Public Class ivitemm
    Inherits _ivitemm

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean

        If Me.LoadByPrimaryKey(oRow!item_code.ToString.Trim) = False Then
            Me.AddNew()
        End If

        '// Salvar Producto
        With Me
            If Not oRow!Abreviada Is DBNull.Value Then .Abreviada = oRow!Abreviada.ToString.Trim
            If Not oRow!Aplicar_Vcmto Is DBNull.Value Then .Aplicar_Vcmto = oRow!Aplicar_Vcmto
            If Not oRow!Asumir_emp Is DBNull.Value Then .Asumir_emp = oRow!Asumir_emp
            If Not oRow!Brand_code Is DBNull.Value Then .Brand_code = oRow!Brand_code
            If Not oRow!Group_code Is DBNull.Value Then .Group_code = oRow!Group_code
            If Not oRow!Imprimir_etiq Is DBNull.Value Then .Imprimir_etiq = oRow!Imprimir_etiq
            If Not oRow!Item_code Is DBNull.Value Then .Item_code = oRow!Item_code
            .s_Item_created = DateTime.Now
            If Not oRow!item_name Is DBNull.Value Then .Item_name = oRow!item_name
            If Not oRow!Item_serial Is DBNull.Value Then .Item_serial = oRow!item_serial
            If Not oRow!Item_serie Is DBNull.Value Then .Item_serie = oRow!item_serie
            If Not oRow!Item_status Is DBNull.Value Then .Item_status = oRow!item_status
            If Not oRow!Prov_code Is DBNull.Value Then .Prov_code = oRow!prov_code
            If Not oRow!Purch_unit Is DBNull.Value Then .Purch_unit = oRow!purch_unit
            If Not oRow!Referencia Is DBNull.Value Then .Referencia = oRow!referencia
            If Not oRow!Sgroup_code Is DBNull.Value Then .Sgroup_code = oRow!sgroup_code
            If Not oRow!Sugerir_compra Is DBNull.Value Then .Sugerir_compra = oRow!Sugerir_compra
            If Not oRow!Sustancias Is DBNull.Value Then .Sustancias = oRow!Sustancias
            If Not oRow!Taxable Is DBNull.Value Then .Taxable = oRow!Taxable
            If Not oRow!Total_onhand Is DBNull.Value Then .Total_onhand = oRow!Total_OnHand
            If Not oRow!Unit_code Is DBNull.Value Then .Unit_code = oRow!unit_code
            If Not oRow!Userid Is DBNull.Value Then .Userid = oRow!userid
            If Not oRow!prd_controlado Is DBNull.Value Then .Prd_controlado = oRow!prd_controlado
            .Item_update = DateTime.Now
            If Not oRow!item_comm Is DBNull.Value Then .Item_comm = oRow!item_comm
            If Not oRow!item_type Is DBNull.Value Then .Item_type = oRow!item_type
            .Save()
        End With
        Return True

    End Function
End Class
