
' Generated by MyGeneration Version # (1.3.0.3)

Public Class ivreferm 
	Inherits _ivreferm

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!ref_code) = False Then
            Me.AddNew()
        End If

        '// Salvar Producto
        With Me
            If Not oRow!Item_code Is DBNull.Value Then .Item_code = oRow!Item_code.ToString.Trim
            If Not oRow!Prov_code Is DBNull.Value Then .Prov_code = oRow!Prov_code
            If Not oRow!Ref_code Is DBNull.Value Then .Ref_code = oRow!Ref_code
            If Not oRow!Refer Is DBNull.Value Then .Refer = oRow!Refer

            .Save()
        End With

        Return True
    End Function

End Class
