
' Generated by MyGeneration Version # (1.3.0.3)

Public Class ivunitd 
	Inherits _ivunitd

    Public Function InsertFromRow(ByVal oRow As DataRow) As Boolean
        If Me.LoadByPrimaryKey(oRow!unit_code, oRow!item_code) = False Then
            Me.AddNew()
        End If

        '// Salvar Producto
        With Me
            If Not oRow!Factor Is DBNull.Value Then .Factor = oRow!Factor.ToString.Trim
            If Not oRow!Item_code Is DBNull.Value Then .Item_code = oRow!Item_code
            If Not oRow!Unit_code Is DBNull.Value Then .Unit_code = oRow!Unit_code
            If Not oRow!Unit_min Is DBNull.Value Then .Unit_min = oRow!Unit_min
            If Not oRow!Unit_type Is DBNull.Value Then .Unit_type = oRow!Unit_type

            .Save()
        End With
        Return True
    End Function

End Class
